---
pool: devpool


trigger:
  - qa

resources:
  repositories:
    - repository: azuredevopsparameters
      endpoint: github.com_srinudammalapati
      ref: 'refs/heads/master'
      name: srinudammalpati/azuredevops
      type: github  
stages:
  - template: azuredevops/azuredevostemplate.yaml@azuredevopsparameters
    parameters:
      goal: package
      javaversion: "1.11"
      javadirectory: /usr/lib/jvm/java-11-openjdk-amd64/
