---
parameters:
  - name: goal
    type: string
    default: package
    values:
      - package
      - clean
      - compile
      - deploy
      - install 
  - name: jdkVersionoption
    type: string
    default: '1.11' 
    values:
      - '1.11'
      - '1.17'
      - '1.8'
  - name: jdkdirectory
    type: string
    default: /usr/lib/jvm/java-11-openjdk-amd64/
    values: 
      - /usr/lib/jvm/java-11-openjdk-amd64/
      - /usr/lib/jvm/java-8-openjdk-amd64/    
  - name: branch
    type: string
    default: main
    values: 
      - master
      - develop  
      - main  

stages:
    - stage: build
      jobs:
        - job:
          steps:
            - task: Maven@3
              inputs:
                mavenPomFile: 'pom.xml'
                goals: "${{parameters.goal}}"
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                jdkVersionOption: "${{parameters.jdkVersionoption}}"
                jdkdirectory: "${{parameters.jdkdirectory}}"